name: 'dbt_hr'
version: '1.0'
config-version: 2

profile: 'dbt_hr'

models:
  dbt_hr:
    staging:
      +schema: staging
      +materialized: view

    marts:
      +schema: marts
      +materialized: table
