#--det berättar för DLT hur den ska prata med Snowflake
[pipeline]
name = "jobtech_ads"
destination = "snowflake"
dataset_name = "STAGING"

[snowflake]
account = "${SNOWFLAKE_ACCOUNT}"
user = "${SNOWFLAKE_USER}"
password = "${SNOWFLAKE_PASSWORD}"
role = "${SNOWFLAKE_ROLE}"
warehouse = "${SNOWFLAKE_WAREHOUSE}"
database = "${SNOWFLAKE_DATABASE}"

[destination.snowflake.credentials]
database = "HR_ANALYTICS"
username = "KANILLA"
password = "DITT_LÖSENORD"  # <-- skriv in ditt riktiga Snowflake-lösenord här
host = "GJDNCHX-YB01210.snowflakecomputing.com"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"

